export const BROTHER_SISTER: Record<string, string[]> = {
  s_posture: ["early_extension", "reverse_spine_angle", "loss_of_posture"],
  c_posture: ["flat_shoulder_plane", "flying_elbow", "loss_of_posture"],
  reverse_spine_angle: ["s_posture", "early_extension", "loss_of_posture", "excessive_spinal_rotation"],
  loss_of_posture: ["s_posture", "reverse_spine_angle", "early_extension", "sway"],
  flat_shoulder_plane: ["c_posture", "reverse_spine_angle", "steep_swing_plane"],
  flying_elbow: ["c_posture", "chicken_winging", "over_the_top"],
  sway: ["slide", "loss_of_posture", "reverse_pivot", "straightening_trail_leg"],
  early_extension: ["s_posture", "loss_of_posture", "over_the_top", "hanging_back"],
  hiking: ["sway", "slide", "reverse_spine_angle"],
  reverse_pivot: ["sway", "loss_of_posture", "straightening_trail_leg"],
  slide: ["sway", "hanging_back", "early_extension"],
  over_the_top: ["early_extension", "casting", "steep_swing_plane", "reverse_spine_angle"],
  casting: ["over_the_top", "scooping", "rolling_wrists", "fat_divots"],
  hanging_back: ["slide", "early_extension", "scooping", "fat_divots"],
  scooping: ["casting", "chicken_winging", "rolling_wrists"],
  chicken_winging: ["flying_elbow", "scooping", "limited_follow_through"],
  excessive_spinal_rotation: ["reverse_spine_angle", "early_extension", "excessive_sidebend"],
  excessive_sidebend: ["excessive_spinal_rotation", "reverse_spine_angle", "hiking"],
  square_feet_stance: ["sway", "slide", "early_extension"],
  right_hip_high: ["s_posture", "reverse_spine_angle", "sway"],
  straightening_trail_leg: ["sway", "reverse_pivot", "loss_of_posture"],
  fat_divots: ["casting", "early_extension", "hanging_back", "over_the_top"],
  steep_swing_plane: ["over_the_top", "flat_shoulder_plane", "trail_arm_vertical"],
  trail_arm_vertical: ["flying_elbow", "steep_swing_plane", "over_the_top"],
  rolling_wrists: ["casting", "scooping", "fat_divots"],
  limited_follow_through: ["chicken_winging", "hanging_back", "early_extension"],
};
