import type { SwingFault } from "@/lib/types";

export const SWING_FAULTS: SwingFault[] = [
  {
    id: "s_posture",
    name: "S-Posture",
    phase: "setup",
    injuryRiskAreas: ["Lower Back", "Hip"],
    tpiManualPage: "L2-001",
  },
  {
    id: "c_posture",
    name: "C-Posture",
    phase: "setup",
    injuryRiskAreas: ["Neck", "Shoulder", "Mid Back"],
    tpiManualPage: "L2-002",
  },
  {
    id: "reverse_spine_angle",
    name: "Reverse Spine Angle",
    phase: "backswing",
    injuryRiskAreas: ["Lower Back", "Hip"],
    tpiManualPage: "L2-003",
  },
  {
    id: "loss_of_posture",
    name: "Loss of Posture",
    phase: "backswing",
    injuryRiskAreas: ["Lower Back", "Hip"],
    tpiManualPage: "L2-004",
  },
  {
    id: "flat_shoulder_plane",
    name: "Flat Shoulder Plane",
    phase: "backswing",
    injuryRiskAreas: ["Shoulder", "Neck"],
    tpiManualPage: "L2-005",
  },
  {
    id: "flying_elbow",
    name: "Flying Elbow",
    phase: "backswing",
    injuryRiskAreas: ["Shoulder", "Elbow"],
    tpiManualPage: "L2-006",
  },
  {
    id: "sway",
    name: "Sway",
    phase: "backswing",
    injuryRiskAreas: ["Hip", "Knee"],
    tpiManualPage: "L2-007",
  },
  {
    id: "early_extension",
    name: "Early Extension",
    phase: "downswing",
    injuryRiskAreas: ["Lower Back", "Hip"],
    tpiManualPage: "L2-008",
  },
  {
    id: "hiking",
    name: "Hiking (Lateral Trunk Flexion)",
    phase: "downswing",
    injuryRiskAreas: ["Lower Back", "Hip"],
    tpiManualPage: "L2-009",
  },
  {
    id: "reverse_pivot",
    name: "Reverse Pivot",
    phase: "backswing",
    injuryRiskAreas: ["Knee", "Lower Back"],
    tpiManualPage: "L2-010",
  },
  {
    id: "slide",
    name: "Slide",
    phase: "downswing",
    injuryRiskAreas: ["Hip", "Knee"],
    tpiManualPage: "L2-011",
  },
  {
    id: "over_the_top",
    name: "Over the Top",
    phase: "downswing",
    injuryRiskAreas: ["Shoulder", "Elbow", "Wrist"],
    tpiManualPage: "L2-012",
  },
  {
    id: "casting",
    name: "Casting / Early Release",
    phase: "downswing",
    injuryRiskAreas: ["Wrist", "Elbow"],
    tpiManualPage: "L2-013",
  },
  {
    id: "hanging_back",
    name: "Hanging Back",
    phase: "downswing",
    injuryRiskAreas: ["Lower Back", "Hip"],
    tpiManualPage: "L2-014",
  },
  {
    id: "scooping",
    name: "Scooping",
    phase: "through_swing",
    injuryRiskAreas: ["Wrist", "Elbow"],
    tpiManualPage: "L2-015",
  },
  {
    id: "chicken_winging",
    name: "Chicken Winging",
    phase: "through_swing",
    injuryRiskAreas: ["Elbow", "Shoulder"],
    tpiManualPage: "L2-016",
  },
  {
    id: "excessive_spinal_rotation",
    name: "Excessive Spinal Rotation",
    phase: "backswing",
    injuryRiskAreas: ["Lower Back", "Thoracic Spine"],
    tpiManualPage: "L2-017",
  },
  {
    id: "excessive_sidebend",
    name: "Excessive Lateral Sidebend",
    phase: "downswing",
    injuryRiskAreas: ["Lower Back", "Thoracic Spine"],
    tpiManualPage: "L2-018",
  },
  {
    id: "square_feet_stance",
    name: "Square Feet Stance",
    phase: "setup",
    injuryRiskAreas: ["Hip", "Knee"],
    tpiManualPage: "L2-019",
  },
  {
    id: "right_hip_high",
    name: "Right Hip High (Pelvic Tilt)",
    phase: "setup",
    injuryRiskAreas: ["Lower Back", "Hip"],
    tpiManualPage: "L2-020",
  },
  {
    id: "straightening_trail_leg",
    name: "Straightening Trail Leg",
    phase: "backswing",
    injuryRiskAreas: ["Hip", "Knee", "Lower Back"],
    tpiManualPage: "L2-021",
  },
  {
    id: "fat_divots",
    name: "Fat Divots (Hitting Behind the Ball)",
    phase: "downswing",
    injuryRiskAreas: ["Wrist", "Elbow", "Lower Back"],
    tpiManualPage: "L2-022",
  },
  {
    id: "steep_swing_plane",
    name: "Steep Swing Plane",
    phase: "downswing",
    injuryRiskAreas: ["Shoulder", "Lower Back"],
    tpiManualPage: "L2-023",
  },
  {
    id: "trail_arm_vertical",
    name: "Trail Arm Going Vertical",
    phase: "backswing",
    injuryRiskAreas: ["Shoulder", "Elbow"],
    tpiManualPage: "L2-024",
  },
  {
    id: "rolling_wrists",
    name: "Rolling Wrists Through Impact",
    phase: "through_swing",
    injuryRiskAreas: ["Wrist", "Forearm"],
    tpiManualPage: "L2-025",
  },
  {
    id: "limited_follow_through",
    name: "Limited Follow-Through",
    phase: "through_swing",
    injuryRiskAreas: ["Shoulder", "Lower Back", "Hip"],
    tpiManualPage: "L2-026",
  },
];
