import type { Exercise } from "@/lib/types";

export const EXERCISE_LIBRARY: Exercise[] = [
  // ═══════════════════════════════════════════════════════════════
  // MULTI-SEGMENTAL EXTENSION (21 exercises)
  // ═══════════════════════════════════════════════════════════════
  {
    name: "Leg Lock Bridge",
    description: "Supine bridge with one leg crossed over the opposite knee to lock lumbar rotation while training hip extension and glute activation in a stable pattern.",
    category: "Glute Activation & Hip Extension",
    dysfunctionType: "SMCD",
    sfmaPattern: "Multi-Segmental Extension",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Assisted Bridge with Mini Band",
    description: "Supine bridge performed with a mini band above the knees providing external cue for hip abduction, reinforcing glute medius and maximus co-contraction during extension.",
    category: "Glute Activation & Hip Extension",
    dysfunctionType: "SMCD",
    sfmaPattern: "Multi-Segmental Extension",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Single-Leg Bridge",
    description: "Unilateral supine bridge challenging pelvic stability and single-leg hip extension strength while exposing asymmetries in glute function.",
    category: "Glute Activation & Hip Extension",
    dysfunctionType: "SMCD",
    sfmaPattern: "Multi-Segmental Extension",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Assisted Bird Dog - Leg slide",
    description: "Quadruped position with one leg sliding posteriorly along the floor, maintaining neutral spine while building foundational core and hip dissociation control.",
    category: "Core Stability & Motor Control",
    dysfunctionType: "SMCD",
    sfmaPattern: "Multi-Segmental Extension",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Assisted Bird Dog - Leg slide with lift",
    description: "Progression from floor slide adding a small hip extension lift at end range to increase demand on lumbo-pelvic stability and glute activation.",
    category: "Core Stability & Motor Control",
    dysfunctionType: "SMCD",
    sfmaPattern: "Multi-Segmental Extension",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Assisted Bird Dog - Leg slide with opposite arm lift",
    description: "Quadruped leg slide combined with contralateral arm elevation, adding an anti-rotation demand and cross-body coordination challenge.",
    category: "Core Stability & Motor Control",
    dysfunctionType: "SMCD",
    sfmaPattern: "Multi-Segmental Extension",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Assisted Bird Dog - Leg slide with lift and opposite arm lift",
    description: "Full contralateral pattern with leg slide, lift, and opposite arm reach, challenging triplanar stability through the trunk while maintaining neutral spine.",
    category: "Core Stability & Motor Control",
    dysfunctionType: "SMCD",
    sfmaPattern: "Multi-Segmental Extension",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Assisted Bird Dog - 90 degree leg lift",
    description: "Quadruped position with hip and knee at 90 degrees, lifting the leg to hip height without lumbar compensation, isolating hip extension motor control.",
    category: "Core Stability & Motor Control",
    dysfunctionType: "SMCD",
    sfmaPattern: "Multi-Segmental Extension",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Bird Dog - Leg Slide",
    description: "Unsupported quadruped leg slide requiring greater proprioceptive demand and trunk stabilization compared to the assisted variant.",
    category: "Core Stability & Motor Control",
    dysfunctionType: "SMCD",
    sfmaPattern: "Multi-Segmental Extension",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Bird Dog - Leg slide with lift",
    description: "Quadruped leg slide with terminal hip extension lift, training the ability to extend the hip without compensatory lumbar extension.",
    category: "Core Stability & Motor Control",
    dysfunctionType: "SMCD",
    sfmaPattern: "Multi-Segmental Extension",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Bird Dog - Leg slide with opposite arm lift",
    description: "Contralateral arm lift added to the leg slide for cross-body stability and anti-rotation demand in the quadruped position.",
    category: "Core Stability & Motor Control",
    dysfunctionType: "SMCD",
    sfmaPattern: "Multi-Segmental Extension",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Bird Dog - 90 degree leg lift",
    description: "Quadruped hip extension with knee maintained at 90 degrees, isolating gluteal function while preventing hamstring dominance.",
    category: "Core Stability & Motor Control",
    dysfunctionType: "SMCD",
    sfmaPattern: "Multi-Segmental Extension",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Bird Dog - Leg Slide with lift and opposite arm lift",
    description: "Full bird dog progression combining leg slide, lift, and contralateral arm reach for maximal cross-body stability challenge.",
    category: "Core Stability & Motor Control",
    dysfunctionType: "SMCD",
    sfmaPattern: "Multi-Segmental Extension",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "T-Spine Rotation with Rib Grab",
    description: "Sidelying thoracic rotation using the hand to anchor the ribcage, providing tactile feedback to isolate segmental thoracic mobility from lumbar compensation.",
    category: "Thoracic Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Multi-Segmental Extension",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "T-Spine Rotation with Reach",
    description: "Sidelying thoracic rotation with arm reach across the body, opening the chest and promoting thoracic extension and rotation range of motion.",
    category: "Thoracic Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Multi-Segmental Extension",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Quadruped T-Spine Rotation",
    description: "Hands-and-knees position rotating through the thoracic spine with one hand behind the head, improving mid-back rotational mobility.",
    category: "Thoracic Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Multi-Segmental Extension",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Quadruped T-Spine Rotation Lumbar Locked",
    description: "Thoracic rotation performed from a sit-back quadruped position locking the lumbar spine, ensuring rotation occurs exclusively at the thoracic segments.",
    category: "Thoracic Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Multi-Segmental Extension",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Rolling Upper Body",
    description: "Supine-to-prone rolling initiated from the upper body, retraining segmental spinal rotation and cross-body coordination patterns.",
    category: "Rolling Patterns",
    dysfunctionType: "SMCD",
    sfmaPattern: "Multi-Segmental Extension",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Rolling Lower Body",
    description: "Supine-to-prone rolling initiated from the lower body, developing hip-driven rotational sequencing and trunk dissociation.",
    category: "Rolling Patterns",
    dysfunctionType: "SMCD",
    sfmaPattern: "Multi-Segmental Extension",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Assisted Rolling Upper Body - Prone to Supine",
    description: "Facilitated upper-body-initiated roll from prone to supine, using manual or equipment assistance to pattern correct segmental sequencing.",
    category: "Rolling Patterns",
    dysfunctionType: "SMCD",
    sfmaPattern: "Multi-Segmental Extension",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Assisted Rolling Lower Body - Prone to Supine",
    description: "Facilitated lower-body-initiated roll from prone to supine, assisting the patient in learning hip-driven rotation without compensatory strategies.",
    category: "Rolling Patterns",
    dysfunctionType: "SMCD",
    sfmaPattern: "Multi-Segmental Extension",
    recommendedForScore: "DN / DP / SMCD",
  },

  // ═══════════════════════════════════════════════════════════════
  // MULTI-SEGMENTAL FLEXION (5 exercises)
  // ═══════════════════════════════════════════════════════════════
  {
    name: "Assisted Leg Lowering to Bolster",
    description: "Supine leg lowering with a bolster as a target, training eccentric control of the hip flexors and core while maintaining pelvic neutral.",
    category: "Hip Flexion Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Multi-Segmental Flexion",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Active Leg Lowering to Bolster",
    description: "Unassisted supine leg lowering to a bolster, progressing active range of motion control for the hamstrings and hip flexors.",
    category: "Hip Flexion Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Multi-Segmental Flexion",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Rolling Upper Body",
    description: "Upper-body-initiated rolling pattern from supine to prone, developing segmental flexion control and cross-body coordination.",
    category: "Rolling Patterns",
    dysfunctionType: "SMCD",
    sfmaPattern: "Multi-Segmental Flexion",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Rolling Lower Body",
    description: "Lower-body-initiated rolling pattern from supine to prone, training pelvic-driven rotation and flexion sequencing.",
    category: "Rolling Patterns",
    dysfunctionType: "SMCD",
    sfmaPattern: "Multi-Segmental Flexion",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Assisted Rolling Upper body - Supine to Prone",
    description: "Facilitated upper-body roll from supine to prone with assistance, guiding the patient through correct flexion-rotation sequencing.",
    category: "Rolling Patterns",
    dysfunctionType: "SMCD",
    sfmaPattern: "Multi-Segmental Flexion",
    recommendedForScore: "DN / DP / SMCD",
  },

  // ═══════════════════════════════════════════════════════════════
  // MULTI-SEGMENTAL ROTATION (22 exercises)
  // ═══════════════════════════════════════════════════════════════
  {
    name: "T-Spine Rotation with Rib Grab",
    description: "Sidelying thoracic rotation with rib anchor providing tactile cueing to isolate thoracic from lumbar rotation.",
    category: "Thoracic Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Multi-Segmental Rotation",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "T-Spine Rotation with Reach",
    description: "Sidelying thoracic rotation with extended arm reach to promote thoracic extension-rotation mobility.",
    category: "Thoracic Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Multi-Segmental Rotation",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Quadruped T-Spine Rotation",
    description: "Hands-and-knees thoracic rotation with hand behind head, targeting mid-back rotational range of motion.",
    category: "Thoracic Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Multi-Segmental Rotation",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Quadruped T-Spine Rotation Lumbar Locked",
    description: "Sit-back quadruped thoracic rotation locking lumbar segments to ensure isolated thoracic rotation gains.",
    category: "Thoracic Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Multi-Segmental Rotation",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Rolling Upper Body",
    description: "Upper-body-initiated rolling for segmental rotation patterning and trunk dissociation training.",
    category: "Rolling Patterns",
    dysfunctionType: "SMCD",
    sfmaPattern: "Multi-Segmental Rotation",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Rolling Lower Body",
    description: "Lower-body-initiated rolling pattern for hip-driven rotational sequencing and trunk coordination.",
    category: "Rolling Patterns",
    dysfunctionType: "SMCD",
    sfmaPattern: "Multi-Segmental Rotation",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Assisted Rolling Upper Body - Prone to Supine",
    description: "Facilitated upper-body rolling from prone to supine, assisting correct rotational sequencing through the trunk.",
    category: "Rolling Patterns",
    dysfunctionType: "SMCD",
    sfmaPattern: "Multi-Segmental Rotation",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Assisted Rolling Lower Body - Prone to Supine",
    description: "Facilitated lower-body rolling from prone to supine, using assistance to guide pelvis-initiated rotation patterns.",
    category: "Rolling Patterns",
    dysfunctionType: "SMCD",
    sfmaPattern: "Multi-Segmental Rotation",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Assisted Rolling Upper body - Supine to Prone",
    description: "Facilitated upper-body rolling from supine to prone, training the flexion-rotation sequence with guided support.",
    category: "Rolling Patterns",
    dysfunctionType: "SMCD",
    sfmaPattern: "Multi-Segmental Rotation",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Tall Kneeling Turns Anterior Load",
    description: "Tall kneeling rotational turns with a weight held anteriorly, challenging anti-rotation stability and trunk rotation motor control.",
    category: "Rotational Motor Control",
    dysfunctionType: "SMCD",
    sfmaPattern: "Multi-Segmental Rotation",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Tall Kneeling Turns Posterior Load",
    description: "Tall kneeling rotational turns with posterior loading, shifting the center of mass to increase rotational stability demand.",
    category: "Rotational Motor Control",
    dysfunctionType: "SMCD",
    sfmaPattern: "Multi-Segmental Rotation",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Quadruped to Half-Kneeling Transitions",
    description: "Dynamic transition from quadruped to half-kneeling integrating rotational control, weight shifting, and postural sequencing.",
    category: "Transitional Patterns",
    dysfunctionType: "SMCD",
    sfmaPattern: "Multi-Segmental Rotation",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Bird Dog - Leg Slide",
    description: "Quadruped leg slide for foundational trunk stability during contralateral limb movement in the rotation pattern context.",
    category: "Core Stability & Motor Control",
    dysfunctionType: "SMCD",
    sfmaPattern: "Multi-Segmental Rotation",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Bird Dog - Leg slide with lift",
    description: "Quadruped leg slide with hip extension lift, building rotational trunk control while maintaining neutral spine alignment.",
    category: "Core Stability & Motor Control",
    dysfunctionType: "SMCD",
    sfmaPattern: "Multi-Segmental Rotation",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Bird Dog - Leg slide with opposite arm lift",
    description: "Cross-body pattern with leg slide and contralateral arm reach, adding anti-rotation demands relevant to rotation dysfunction.",
    category: "Core Stability & Motor Control",
    dysfunctionType: "SMCD",
    sfmaPattern: "Multi-Segmental Rotation",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Bird Dog - 90 degree leg lift",
    description: "Quadruped hip extension at 90 degrees knee flexion, isolating glute from hamstring contribution during trunk rotation control.",
    category: "Core Stability & Motor Control",
    dysfunctionType: "SMCD",
    sfmaPattern: "Multi-Segmental Rotation",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Bird Dog - Leg Slide with lift and opposite arm lift",
    description: "Full contralateral bird dog combining all progressions for maximal anti-rotation and cross-body stability challenge.",
    category: "Core Stability & Motor Control",
    dysfunctionType: "SMCD",
    sfmaPattern: "Multi-Segmental Rotation",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Assisted Bird Dog - Leg slide",
    description: "Supported quadruped leg slide providing a regression for patients unable to maintain neutral spine during contralateral movement.",
    category: "Core Stability & Motor Control",
    dysfunctionType: "SMCD",
    sfmaPattern: "Multi-Segmental Rotation",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Assisted Bird Dog - Leg slide with lift",
    description: "Supported leg slide with terminal hip extension, grading the anti-rotation demand for rotational motor control re-education.",
    category: "Core Stability & Motor Control",
    dysfunctionType: "SMCD",
    sfmaPattern: "Multi-Segmental Rotation",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Assisted Bird Dog - Leg slide with opposite arm lift",
    description: "Supported cross-body pattern integrating arm reach with leg slide for graded rotational stability training.",
    category: "Core Stability & Motor Control",
    dysfunctionType: "SMCD",
    sfmaPattern: "Multi-Segmental Rotation",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Assisted Bird Dog - Leg slide with lift and opposite arm lift",
    description: "Full assisted contralateral pattern combining leg and arm movements for comprehensive rotational motor control.",
    category: "Core Stability & Motor Control",
    dysfunctionType: "SMCD",
    sfmaPattern: "Multi-Segmental Rotation",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Assisted Bird Dog - 90 degree leg lift",
    description: "Supported quadruped 90-degree hip extension, providing a graded entry point for rotational stability retraining.",
    category: "Core Stability & Motor Control",
    dysfunctionType: "SMCD",
    sfmaPattern: "Multi-Segmental Rotation",
    recommendedForScore: "DN / DP / SMCD",
  },

  // ═══════════════════════════════════════════════════════════════
  // ROTARY STABILITY (18 exercises)
  // ═══════════════════════════════════════════════════════════════
  {
    name: "Rolling Upper Body",
    description: "Upper-body-initiated rolling to retrain fundamental rotational patterns relevant to rotary stability.",
    category: "Rolling Patterns",
    dysfunctionType: "SMCD",
    sfmaPattern: "Rotary Stability",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Rolling Lower Body",
    description: "Lower-body-initiated rolling to develop pelvic rotational control foundational to rotary stability.",
    category: "Rolling Patterns",
    dysfunctionType: "SMCD",
    sfmaPattern: "Rotary Stability",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Assisted Rolling Upper Body - Prone to Supine",
    description: "Facilitated prone-to-supine upper-body roll to guide rotational motor patterns for rotary stability deficits.",
    category: "Rolling Patterns",
    dysfunctionType: "SMCD",
    sfmaPattern: "Rotary Stability",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Assisted Rolling Lower Body - Prone to Supine",
    description: "Facilitated prone-to-supine lower-body roll to retrain pelvic-driven rotation for rotary stability.",
    category: "Rolling Patterns",
    dysfunctionType: "SMCD",
    sfmaPattern: "Rotary Stability",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Assisted Rolling Upper body - Supine to Prone",
    description: "Facilitated supine-to-prone upper-body roll progressing rotational sequencing for rotary stability.",
    category: "Rolling Patterns",
    dysfunctionType: "SMCD",
    sfmaPattern: "Rotary Stability",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Bird Dog - Leg Slide",
    description: "Quadruped leg slide building anti-rotation trunk stability relevant to rotary stability demands.",
    category: "Core Stability & Motor Control",
    dysfunctionType: "SMCD",
    sfmaPattern: "Rotary Stability",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Bird Dog - Leg slide with lift",
    description: "Quadruped leg slide with hip extension targeting rotary stability through progressive trunk loading.",
    category: "Core Stability & Motor Control",
    dysfunctionType: "SMCD",
    sfmaPattern: "Rotary Stability",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Bird Dog - Leg slide with opposite arm lift",
    description: "Cross-body quadruped pattern with maximal anti-rotation demand for rotary stability training.",
    category: "Core Stability & Motor Control",
    dysfunctionType: "SMCD",
    sfmaPattern: "Rotary Stability",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Bird Dog - 90 degree leg lift",
    description: "Quadruped 90-degree hip extension isolating gluteal from hamstring contribution during rotary stability work.",
    category: "Core Stability & Motor Control",
    dysfunctionType: "SMCD",
    sfmaPattern: "Rotary Stability",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Bird Dog - Leg Slide with lift and opposite arm lift",
    description: "Full contralateral bird dog for maximum rotary stability challenge with cross-body coordination.",
    category: "Core Stability & Motor Control",
    dysfunctionType: "SMCD",
    sfmaPattern: "Rotary Stability",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Assisted Bird Dog - Leg slide",
    description: "Supported quadruped leg slide as a regression for rotary stability motor control retraining.",
    category: "Core Stability & Motor Control",
    dysfunctionType: "SMCD",
    sfmaPattern: "Rotary Stability",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Assisted Bird Dog - Leg slide with lift",
    description: "Supported leg slide with lift grading rotary stability demands for progressive motor control.",
    category: "Core Stability & Motor Control",
    dysfunctionType: "SMCD",
    sfmaPattern: "Rotary Stability",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Assisted Bird Dog - Leg slide with opposite arm lift",
    description: "Supported cross-body quadruped pattern for rotary stability retraining with reduced demand.",
    category: "Core Stability & Motor Control",
    dysfunctionType: "SMCD",
    sfmaPattern: "Rotary Stability",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Assisted Bird Dog - Leg slide with lift and opposite arm lift",
    description: "Full assisted contralateral quadruped pattern for comprehensive rotary stability re-education.",
    category: "Core Stability & Motor Control",
    dysfunctionType: "SMCD",
    sfmaPattern: "Rotary Stability",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Assisted Bird Dog - 90 degree leg lift",
    description: "Supported 90-degree hip extension in quadruped, providing entry-level rotary stability training.",
    category: "Core Stability & Motor Control",
    dysfunctionType: "SMCD",
    sfmaPattern: "Rotary Stability",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "T-Spine Rotation with Rib Grab",
    description: "Sidelying thoracic rotation with rib grab addressing mobility restrictions that contribute to rotary stability deficits.",
    category: "Thoracic Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Rotary Stability",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "T-Spine Rotation with Reach",
    description: "Sidelying thoracic rotation with reach to restore mid-back mobility contributing to rotary stability limitations.",
    category: "Thoracic Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Rotary Stability",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Quadruped T-Spine Rotation Lumbar Locked",
    description: "Lumbar-locked thoracic rotation addressing thoracic mobility restrictions underlying rotary stability dysfunction.",
    category: "Thoracic Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Rotary Stability",
    recommendedForScore: "DN / DP / MD",
  },

  // ═══════════════════════════════════════════════════════════════
  // SHOULDER MOBILITY (27 exercises)
  // ═══════════════════════════════════════════════════════════════
  {
    name: "Sidelying Shoulder ER at 0 Degrees",
    description: "Sidelying external rotation with arm at the side, isolating infraspinatus and teres minor activation with minimal impingement risk.",
    category: "Rotator Cuff Activation",
    dysfunctionType: "SMCD",
    sfmaPattern: "Shoulder Mobility",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Sidelying Shoulder IR at 0 Degrees",
    description: "Sidelying internal rotation with arm at the side, training subscapularis activation in a stable joint position.",
    category: "Rotator Cuff Activation",
    dysfunctionType: "SMCD",
    sfmaPattern: "Shoulder Mobility",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Prone Y Raise",
    description: "Prone arm elevation in a Y pattern targeting lower trapezius activation and scapular upward rotation control.",
    category: "Scapular Stability",
    dysfunctionType: "SMCD",
    sfmaPattern: "Shoulder Mobility",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Prone T Raise",
    description: "Prone arm elevation in a T pattern targeting middle trapezius and rhomboid activation for scapular retraction.",
    category: "Scapular Stability",
    dysfunctionType: "SMCD",
    sfmaPattern: "Shoulder Mobility",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Prone W Raise",
    description: "Prone arm elevation in a W pattern targeting external rotators and lower trapezius in a shortened range.",
    category: "Scapular Stability",
    dysfunctionType: "SMCD",
    sfmaPattern: "Shoulder Mobility",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Wall Slide",
    description: "Standing wall slide promoting scapular upward rotation, serratus anterior activation, and overhead mobility patterning.",
    category: "Scapular Stability",
    dysfunctionType: "SMCD",
    sfmaPattern: "Shoulder Mobility",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Floor Slide",
    description: "Supine floor slide providing a supported surface for scapular mobility and overhead reaching pattern correction.",
    category: "Scapular Stability",
    dysfunctionType: "SMCD",
    sfmaPattern: "Shoulder Mobility",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Quadruped Shoulder Flexion Lift-Off",
    description: "Quadruped arm lift-off training shoulder flexion motor control with scapular stabilization in a closed-chain position.",
    category: "Scapular Stability",
    dysfunctionType: "SMCD",
    sfmaPattern: "Shoulder Mobility",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Half-Kneeling Overhead Press",
    description: "Overhead press from half-kneeling combining shoulder mobility with core stability and proper scapulohumeral rhythm.",
    category: "Overhead Patterns",
    dysfunctionType: "SMCD",
    sfmaPattern: "Shoulder Mobility",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Tall Kneeling Kettlebell Arm Bar",
    description: "Kettlebell arm bar from tall kneeling, loading shoulder stability through full range with rotator cuff and scapular co-contraction.",
    category: "Shoulder Stability",
    dysfunctionType: "SMCD",
    sfmaPattern: "Shoulder Mobility",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Supine Kettlebell Arm Bar",
    description: "Supine arm bar with kettlebell for loaded shoulder stabilization, promoting glenohumeral centration and posterior capsule mobility.",
    category: "Shoulder Stability",
    dysfunctionType: "SMCD",
    sfmaPattern: "Shoulder Mobility",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Turkish Get-Up (Partial - to Elbow)",
    description: "Partial get-up to elbow with load overhead, integrating shoulder stability with trunk rotation and core activation.",
    category: "Integrated Patterns",
    dysfunctionType: "SMCD",
    sfmaPattern: "Shoulder Mobility",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Sleeper Stretch",
    description: "Sidelying internal rotation stretch targeting posterior shoulder capsule tightness and restoring glenohumeral IR range.",
    category: "Glenohumeral Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Shoulder Mobility",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Cross-Body Stretch",
    description: "Horizontal adduction stretch addressing posterior capsule and infraspinatus tightness limiting internal rotation and cross-body reach.",
    category: "Glenohumeral Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Shoulder Mobility",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Doorway Pec Stretch",
    description: "Doorway stretch targeting pectoralis major and minor tightness that restricts shoulder horizontal abduction and external rotation.",
    category: "Anterior Shoulder Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Shoulder Mobility",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Lat Stretch on Wall",
    description: "Wall-supported latissimus dorsi stretch addressing overhead mobility restrictions from lat tightness.",
    category: "Posterior Chain Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Shoulder Mobility",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Foam Roll Thoracic Extension",
    description: "Thoracic spine extension over foam roller to restore upper back extension range needed for full overhead shoulder mobility.",
    category: "Thoracic Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Shoulder Mobility",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Foam Roll Lat",
    description: "Latissimus dorsi soft tissue mobilization with foam roller to address tissue extensibility limiting overhead range.",
    category: "Soft Tissue Mobilization",
    dysfunctionType: "MD",
    sfmaPattern: "Shoulder Mobility",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Prone Shoulder Flexion on Bench",
    description: "Prone shoulder flexion with arm hanging off bench, using gravity to promote overhead shoulder range and scapular mobility.",
    category: "Glenohumeral Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Shoulder Mobility",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Band-Assisted Shoulder Flexion",
    description: "Resistance band providing joint distraction during flexion to improve glenohumeral mobility with proper arthrokinematics.",
    category: "Glenohumeral Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Shoulder Mobility",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Supine Passive Shoulder ER at 90 Degrees",
    description: "Passive external rotation at 90 degrees abduction restoring ER range for functional overhead and throwing positions.",
    category: "Glenohumeral Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Shoulder Mobility",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Supine Passive Shoulder IR at 90 Degrees",
    description: "Passive internal rotation at 90 degrees abduction addressing posterior capsule tightness and GIRD.",
    category: "Glenohumeral Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Shoulder Mobility",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Quadruped Rock Back with Arms Overhead",
    description: "Rocking back in quadruped with arms extended overhead to promote combined shoulder flexion with thoracic extension mobility.",
    category: "Integrated Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Shoulder Mobility",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Open Book Stretch",
    description: "Sidelying thoracic rotation with arm opening to full rotation, promoting combined thoracic and shoulder mobility.",
    category: "Thoracic Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Shoulder Mobility",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Prone Shoulder 90/90 ER Isometric",
    description: "Isometric external rotation at 90/90 position training rotator cuff endurance and stability in a functional range.",
    category: "Rotator Cuff Activation",
    dysfunctionType: "SMCD",
    sfmaPattern: "Shoulder Mobility",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Standing Cable ER",
    description: "Standing external rotation with cable resistance for rotator cuff strengthening in an upright functional position.",
    category: "Rotator Cuff Strengthening",
    dysfunctionType: "SMCD",
    sfmaPattern: "Shoulder Mobility",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Push-Up Plus",
    description: "Push-up with additional scapular protraction at the top, targeting serratus anterior activation for scapular stability.",
    category: "Scapular Stability",
    dysfunctionType: "SMCD",
    sfmaPattern: "Shoulder Mobility",
    recommendedForScore: "DN / DP / SMCD",
  },

  // ═══════════════════════════════════════════════════════════════
  // SINGLE LEG STANCE (22 exercises)
  // ═══════════════════════════════════════════════════════════════
  {
    name: "Assisted Single-Leg Balance (Eyes Open)",
    description: "Single-leg balance with light support to develop foundational proprioceptive control and ankle strategy awareness.",
    category: "Balance & Proprioception",
    dysfunctionType: "SMCD",
    sfmaPattern: "Single Leg Stance",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Single-Leg Balance (Eyes Closed)",
    description: "Eyes-closed single-leg balance progressing vestibular and somatosensory reliance for postural control.",
    category: "Balance & Proprioception",
    dysfunctionType: "SMCD",
    sfmaPattern: "Single Leg Stance",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Single-Leg Balance on Foam Pad",
    description: "Single-leg balance on an unstable surface challenging ankle strategy and proprioceptive adaptation.",
    category: "Balance & Proprioception",
    dysfunctionType: "SMCD",
    sfmaPattern: "Single Leg Stance",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Tandem Stance Progression",
    description: "Heel-to-toe stance progressing from static to dynamic conditions to train narrow base-of-support balance.",
    category: "Balance & Proprioception",
    dysfunctionType: "SMCD",
    sfmaPattern: "Single Leg Stance",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Half-Kneeling Hip Flexor Stretch",
    description: "Half-kneeling stretch targeting iliopsoas and rectus femoris tightness that limits hip extension during single-leg stance.",
    category: "Hip Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Single Leg Stance",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Standing Calf Stretch (Gastrocnemius)",
    description: "Wall stretch targeting gastrocnemius length restriction that limits ankle dorsiflexion during single-leg stance.",
    category: "Ankle Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Single Leg Stance",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Standing Calf Stretch (Soleus)",
    description: "Wall stretch with bent knee targeting soleus length restriction limiting deep dorsiflexion.",
    category: "Ankle Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Single Leg Stance",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Half-Kneeling Ankle Dorsiflexion Mobilization",
    description: "Half-kneeling ankle mobilization driving the knee over the toes to restore talocrural joint dorsiflexion range.",
    category: "Ankle Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Single Leg Stance",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Banded Ankle Dorsiflexion",
    description: "Band-assisted ankle dorsiflexion providing posterior talar glide to address joint restriction limiting dorsiflexion.",
    category: "Ankle Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Single Leg Stance",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Foam Roll Calf",
    description: "Calf soft tissue mobilization with foam roller addressing tissue extensibility that restricts ankle motion.",
    category: "Soft Tissue Mobilization",
    dysfunctionType: "MD",
    sfmaPattern: "Single Leg Stance",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Single-Leg Romanian Deadlift",
    description: "Unilateral hip hinge developing posterior chain strength and single-leg stability through full hip range.",
    category: "Hip Stability & Strength",
    dysfunctionType: "SMCD",
    sfmaPattern: "Single Leg Stance",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Lateral Band Walk",
    description: "Side-stepping with mini band above ankles targeting gluteus medius activation for frontal plane pelvic stability.",
    category: "Hip Stability & Strength",
    dysfunctionType: "SMCD",
    sfmaPattern: "Single Leg Stance",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Clamshell",
    description: "Sidelying hip external rotation with knees bent, isolating gluteus medius activation for hip stability.",
    category: "Hip Stability & Strength",
    dysfunctionType: "SMCD",
    sfmaPattern: "Single Leg Stance",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Side-Lying Hip Abduction",
    description: "Sidelying hip abduction targeting gluteus medius strength for single-leg pelvic stability control.",
    category: "Hip Stability & Strength",
    dysfunctionType: "SMCD",
    sfmaPattern: "Single Leg Stance",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Single-Leg Bridge",
    description: "Unilateral bridge for hip extension strength and pelvic stability relevant to single-leg stance control.",
    category: "Hip Stability & Strength",
    dysfunctionType: "SMCD",
    sfmaPattern: "Single Leg Stance",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Step-Down from Box",
    description: "Controlled step-down eccentrically loading the stance leg while maintaining pelvic and knee alignment.",
    category: "Functional Strength",
    dysfunctionType: "SMCD",
    sfmaPattern: "Single Leg Stance",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Single-Leg Hop to Stabilization",
    description: "Dynamic single-leg hop with stabilization upon landing, integrating reactive balance and force absorption.",
    category: "Dynamic Balance",
    dysfunctionType: "SMCD",
    sfmaPattern: "Single Leg Stance",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Ankle Inversion Strengthening (Band)",
    description: "Resisted ankle inversion with band targeting tibialis posterior and medial ankle stabilizers.",
    category: "Ankle Stability",
    dysfunctionType: "SMCD",
    sfmaPattern: "Single Leg Stance",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Ankle Eversion Strengthening (Band)",
    description: "Resisted ankle eversion with band targeting peroneals for lateral ankle stability and injury prevention.",
    category: "Ankle Stability",
    dysfunctionType: "SMCD",
    sfmaPattern: "Single Leg Stance",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Seated Ankle Circles",
    description: "Active ankle circumduction restoring multi-planar ankle mobility and promoting joint lubrication.",
    category: "Ankle Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Single Leg Stance",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Towel Scrunch",
    description: "Intrinsic foot strengthening by scrunching a towel with the toes, supporting the foot arch and ankle stability.",
    category: "Foot & Ankle Stability",
    dysfunctionType: "SMCD",
    sfmaPattern: "Single Leg Stance",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Short Foot Exercise",
    description: "Intrinsic foot muscle activation drawing the metatarsal heads toward the heel without toe flexion to support arch control.",
    category: "Foot & Ankle Stability",
    dysfunctionType: "SMCD",
    sfmaPattern: "Single Leg Stance",
    recommendedForScore: "DN / DP / SMCD",
  },

  // ═══════════════════════════════════════════════════════════════
  // TRUNK STABILITY PUSH-UP (11 exercises)
  // ═══════════════════════════════════════════════════════════════
  {
    name: "Elevated Push-Up",
    description: "Push-up with hands elevated on a bench reducing load while training trunk stability through pressing.",
    category: "Pressing Patterns",
    dysfunctionType: "SMCD",
    sfmaPattern: "Trunk Stability Push-Up",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Quadruped Diagonals",
    description: "Contralateral arm and leg lifts from quadruped training trunk stability and cross-body coordination.",
    category: "Core Stability & Motor Control",
    dysfunctionType: "SMCD",
    sfmaPattern: "Trunk Stability Push-Up",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Plank Hold",
    description: "Isometric prone plank developing trunk endurance and anti-extension core stability.",
    category: "Core Stability & Motor Control",
    dysfunctionType: "SMCD",
    sfmaPattern: "Trunk Stability Push-Up",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Side Plank Hold",
    description: "Isometric side plank training lateral trunk stability and oblique endurance.",
    category: "Core Stability & Motor Control",
    dysfunctionType: "SMCD",
    sfmaPattern: "Trunk Stability Push-Up",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Dead Bug",
    description: "Supine contralateral limb lowering maintaining lumbar-pelvic neutral while challenging anti-extension control.",
    category: "Core Stability & Motor Control",
    dysfunctionType: "SMCD",
    sfmaPattern: "Trunk Stability Push-Up",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Push-Up Plus",
    description: "Push-up with scapular protraction at top range, integrating serratus anterior activation with trunk stability.",
    category: "Pressing Patterns",
    dysfunctionType: "SMCD",
    sfmaPattern: "Trunk Stability Push-Up",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Tall Kneeling Pallof Press",
    description: "Anti-rotation press from tall kneeling position training core stability against rotational forces.",
    category: "Anti-Rotation",
    dysfunctionType: "SMCD",
    sfmaPattern: "Trunk Stability Push-Up",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Rolling Upper Body",
    description: "Upper-body-initiated rolling retraining fundamental trunk stability and rotational sequencing patterns.",
    category: "Rolling Patterns",
    dysfunctionType: "SMCD",
    sfmaPattern: "Trunk Stability Push-Up",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Rolling Lower Body",
    description: "Lower-body-initiated rolling for pelvic-driven trunk stability and motor control re-education.",
    category: "Rolling Patterns",
    dysfunctionType: "SMCD",
    sfmaPattern: "Trunk Stability Push-Up",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "T-Spine Rotation with Rib Grab",
    description: "Sidelying thoracic rotation targeting thoracic mobility that may limit trunk stability push-up performance.",
    category: "Thoracic Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Trunk Stability Push-Up",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Foam Roll Thoracic Extension",
    description: "Thoracic extension over foam roller to restore extension range necessary for optimal push-up positioning.",
    category: "Thoracic Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Trunk Stability Push-Up",
    recommendedForScore: "DN / DP / MD",
  },

  // ═══════════════════════════════════════════════════════════════
  // UPPER EXTREMITY PATTERNS (6 exercises)
  // ═══════════════════════════════════════════════════════════════
  {
    name: "T-Spine Rotation with Rib Grab",
    description: "Sidelying thoracic rotation with rib anchor to address thoracic mobility restrictions affecting UE patterns.",
    category: "Thoracic Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Upper Extremity Patterns",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "T-Spine Rotation with Reach",
    description: "Sidelying thoracic rotation with arm reach addressing thoracic extension-rotation limitations in UE patterns.",
    category: "Thoracic Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Upper Extremity Patterns",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Quadruped T-Spine Rotation",
    description: "Hands-and-knees thoracic rotation targeting mid-back mobility relevant to upper extremity movement patterns.",
    category: "Thoracic Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Upper Extremity Patterns",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Quadruped T-Spine Rotation Lumbar Locked",
    description: "Lumbar-locked quadruped thoracic rotation isolating thoracic segments that influence UE pattern performance.",
    category: "Thoracic Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Upper Extremity Patterns",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Rolling Upper Body",
    description: "Upper-body-initiated rolling for retraining trunk-UE coordination and segmental control patterns.",
    category: "Rolling Patterns",
    dysfunctionType: "SMCD",
    sfmaPattern: "Upper Extremity Patterns",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Rolling Lower Body",
    description: "Lower-body-initiated rolling developing hip-trunk dissociation relevant to UE pattern dysfunction.",
    category: "Rolling Patterns",
    dysfunctionType: "SMCD",
    sfmaPattern: "Upper Extremity Patterns",
    recommendedForScore: "DN / DP / SMCD",
  },

  // ═══════════════════════════════════════════════════════════════
  // CERVICAL PATTERNS (15 exercises)
  // ═══════════════════════════════════════════════════════════════
  {
    name: "Supine Chin Tuck (Deep Cervical Flexor Activation)",
    description: "Supine chin tuck activating deep cervical flexors (longus colli/capitis) to improve cervical motor control and reduce upper trapezius dominance.",
    category: "Deep Cervical Stability",
    dysfunctionType: "SMCD",
    sfmaPattern: "Cervical Patterns",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Supine Head Nod (Cranio-Cervical Flexion)",
    description: "Small nodding motion activating the cranio-cervical flexors, addressing OA joint motor control deficits.",
    category: "Deep Cervical Stability",
    dysfunctionType: "SMCD",
    sfmaPattern: "Cervical Patterns",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Prone Chin Tuck with Lift",
    description: "Prone chin tuck with cervical extension targeting deep neck flexor endurance and cervical extensor co-contraction.",
    category: "Cervical Motor Control",
    dysfunctionType: "SMCD",
    sfmaPattern: "Cervical Patterns",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Cervical Rotation AROM with Chin Tuck",
    description: "Active cervical rotation maintaining chin tuck position, retraining rotation with proper deep flexor engagement.",
    category: "Cervical Motor Control",
    dysfunctionType: "SMCD",
    sfmaPattern: "Cervical Patterns",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Cervical Extension AROM (Supine)",
    description: "Supine cervical extension through available range, using gravity-eliminated position for safe extension training.",
    category: "Cervical Motor Control",
    dysfunctionType: "SMCD",
    sfmaPattern: "Cervical Patterns",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Isometric Cervical Flexion",
    description: "Hand-resisted isometric cervical flexion building deep cervical flexor endurance in a neutral position.",
    category: "Cervical Strengthening",
    dysfunctionType: "SMCD",
    sfmaPattern: "Cervical Patterns",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Isometric Cervical Extension",
    description: "Hand-resisted isometric cervical extension building cervical extensor endurance and co-contraction stability.",
    category: "Cervical Strengthening",
    dysfunctionType: "SMCD",
    sfmaPattern: "Cervical Patterns",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Isometric Cervical Rotation",
    description: "Hand-resisted isometric rotation building rotational muscle endurance and cervical stability.",
    category: "Cervical Strengthening",
    dysfunctionType: "SMCD",
    sfmaPattern: "Cervical Patterns",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Cervical Flexion Passive Stretch",
    description: "Gentle passive cervical flexion stretch addressing mid-to-lower cervical extension restrictions.",
    category: "Cervical Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Cervical Patterns",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Cervical Extension Passive Stretch",
    description: "Gentle passive cervical extension stretch restoring extension range limited by anterior cervical tightness.",
    category: "Cervical Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Cervical Patterns",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Cervical Rotation Passive Stretch",
    description: "Gentle passive cervical rotation stretch addressing rotational restrictions at mid-cervical and C1-C2 segments.",
    category: "Cervical Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Cervical Patterns",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Upper Trapezius Stretch",
    description: "Seated or standing lateral cervical flexion stretch targeting upper trapezius and levator scapulae tightness.",
    category: "Cervical Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Cervical Patterns",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Levator Scapulae Stretch",
    description: "Stretch targeting the levator scapulae by combining cervical flexion, rotation, and lateral flexion to isolate the muscle.",
    category: "Cervical Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Cervical Patterns",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Suboccipital Self-Release",
    description: "Self-mobilization of suboccipital muscles using a ball or fingers to address OA joint restrictions and headache triggers.",
    category: "Soft Tissue Mobilization",
    dysfunctionType: "MD",
    sfmaPattern: "Cervical Patterns",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Cervical Retraction/Protraction AROM",
    description: "Active cervical retraction and protraction restoring sagittal plane cervical mobility and postural awareness.",
    category: "Cervical Motor Control",
    dysfunctionType: "SMCD",
    sfmaPattern: "Cervical Patterns",
    recommendedForScore: "DN / DP / SMCD",
  },

  // ═══════════════════════════════════════════════════════════════
  // OVERHEAD DEEP SQUAT (23 exercises)
  // ═══════════════════════════════════════════════════════════════
  {
    name: "Goblet Squat",
    description: "Front-loaded squat with weight held at chest, promoting upright torso, proper squat depth, and hip mobility.",
    category: "Squat Patterns",
    dysfunctionType: "SMCD",
    sfmaPattern: "Overhead Deep Squat",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Assisted Overhead Squat",
    description: "Overhead squat with band or TRX assistance allowing the patient to reach full depth with reduced load demands.",
    category: "Squat Patterns",
    dysfunctionType: "SMCD",
    sfmaPattern: "Overhead Deep Squat",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Bodyweight Squat to Box",
    description: "Squat to a box target providing a depth cue and reducing anxiety about deep squat positions.",
    category: "Squat Patterns",
    dysfunctionType: "SMCD",
    sfmaPattern: "Overhead Deep Squat",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Half-Kneeling Ankle Dorsiflexion Mobilization",
    description: "Half-kneeling ankle mobilization to improve talocrural dorsiflexion needed for full squat depth.",
    category: "Ankle Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Overhead Deep Squat",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Banded Ankle Dorsiflexion",
    description: "Band-assisted dorsiflexion with posterior talar glide addressing joint restrictions limiting squat depth.",
    category: "Ankle Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Overhead Deep Squat",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Standing Calf Stretch (Gastrocnemius)",
    description: "Wall-based gastrocnemius stretch to restore ankle dorsiflexion range needed for deep squat.",
    category: "Ankle Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Overhead Deep Squat",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Standing Calf Stretch (Soleus)",
    description: "Bent-knee wall stretch targeting soleus length restrictions limiting ankle dorsiflexion in the squat.",
    category: "Ankle Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Overhead Deep Squat",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "90/90 Hip IR Stretch",
    description: "Seated 90/90 position stretch targeting hip internal rotation required for proper squat mechanics.",
    category: "Hip Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Overhead Deep Squat",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "90/90 Hip ER Stretch",
    description: "Seated 90/90 position stretch targeting hip external rotation for balanced hip mobility in the squat.",
    category: "Hip Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Overhead Deep Squat",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Supine Figure-4 Stretch",
    description: "Supine piriformis and hip external rotator stretch addressing posterior hip tightness limiting squat depth.",
    category: "Hip Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Overhead Deep Squat",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Adductor Rockback Stretch",
    description: "Quadruped hip adductor stretch rocking back to increase inner thigh length needed for squat width and depth.",
    category: "Hip Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Overhead Deep Squat",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Deep Squat Hold with Support",
    description: "Prolonged deep squat hold using a doorframe or rack for support to promote hip, ankle, and thoracic mobility simultaneously.",
    category: "Integrated Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Overhead Deep Squat",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Leg Lock Bridge",
    description: "Leg-locked supine bridge training glute activation and hip extension patterning relevant to squat performance.",
    category: "Glute Activation",
    dysfunctionType: "SMCD",
    sfmaPattern: "Overhead Deep Squat",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Assisted Bird Dog - Leg slide",
    description: "Quadruped leg slide for core stability supporting proper trunk control during squat movement.",
    category: "Core Stability",
    dysfunctionType: "SMCD",
    sfmaPattern: "Overhead Deep Squat",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Rolling Upper Body",
    description: "Upper-body rolling to retrain trunk mobility and motor control patterns foundational to squat performance.",
    category: "Rolling Patterns",
    dysfunctionType: "SMCD",
    sfmaPattern: "Overhead Deep Squat",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Rolling Lower Body",
    description: "Lower-body rolling to develop hip-driven patterning and pelvic control for squat mechanics.",
    category: "Rolling Patterns",
    dysfunctionType: "SMCD",
    sfmaPattern: "Overhead Deep Squat",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Foam Roll Calf",
    description: "Calf soft tissue mobilization addressing gastrocnemius-soleus extensibility for improved squat dorsiflexion.",
    category: "Soft Tissue Mobilization",
    dysfunctionType: "MD",
    sfmaPattern: "Overhead Deep Squat",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Foam Roll Adductors",
    description: "Adductor soft tissue mobilization using foam roller to improve inner thigh extensibility for squat depth.",
    category: "Soft Tissue Mobilization",
    dysfunctionType: "MD",
    sfmaPattern: "Overhead Deep Squat",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Foam Roll Quadriceps",
    description: "Quadriceps soft tissue mobilization addressing anterior thigh tightness that restricts knee flexion in the squat.",
    category: "Soft Tissue Mobilization",
    dysfunctionType: "MD",
    sfmaPattern: "Overhead Deep Squat",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Wall Sit Hold",
    description: "Isometric wall sit building quadriceps endurance and motor control in a closed-chain squat position.",
    category: "Squat Strength",
    dysfunctionType: "SMCD",
    sfmaPattern: "Overhead Deep Squat",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Split Squat",
    description: "Bilateral stance split position squat addressing unilateral hip and knee strength for balanced squat mechanics.",
    category: "Squat Patterns",
    dysfunctionType: "SMCD",
    sfmaPattern: "Overhead Deep Squat",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "T-Spine Rotation with Rib Grab",
    description: "Thoracic rotation mobility addressing thoracic restrictions that prevent upright posture during overhead squat.",
    category: "Thoracic Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Overhead Deep Squat",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Foam Roll Thoracic Extension",
    description: "Thoracic extension over foam roller restoring upper back extension for proper overhead squat trunk positioning.",
    category: "Thoracic Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Overhead Deep Squat",
    recommendedForScore: "DN / DP / MD",
  },

  // ═══════════════════════════════════════════════════════════════
  // HURDLE STEP (18 exercises)
  // ═══════════════════════════════════════════════════════════════
  {
    name: "Single-Leg Balance (Eyes Open)",
    description: "Foundational single-leg stance building the proprioceptive base needed for hurdle step stability.",
    category: "Balance & Proprioception",
    dysfunctionType: "SMCD",
    sfmaPattern: "Hurdle Step",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Single-Leg Balance (Eyes Closed)",
    description: "Progressed single-leg balance removing visual input to increase vestibular and somatosensory demand.",
    category: "Balance & Proprioception",
    dysfunctionType: "SMCD",
    sfmaPattern: "Hurdle Step",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Standing Hip Flexion March",
    description: "Standing march with controlled hip flexion, training single-leg stance stability with reciprocal hip movement.",
    category: "Hip Motor Control",
    dysfunctionType: "SMCD",
    sfmaPattern: "Hurdle Step",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Lateral Band Walk",
    description: "Resisted side-stepping for gluteus medius activation essential for frontal plane stability during hurdle step.",
    category: "Hip Stability",
    dysfunctionType: "SMCD",
    sfmaPattern: "Hurdle Step",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Leg Lock Bridge",
    description: "Leg-locked bridge for glute activation and hip extension motor control relevant to stance phase stability.",
    category: "Glute Activation",
    dysfunctionType: "SMCD",
    sfmaPattern: "Hurdle Step",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Single-Leg Bridge",
    description: "Unilateral bridge for hip extension strength needed to maintain pelvic level during single-leg hurdle step.",
    category: "Hip Stability",
    dysfunctionType: "SMCD",
    sfmaPattern: "Hurdle Step",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Half-Kneeling Hip Flexor Stretch",
    description: "Hip flexor stretch restoring hip extension range needed for proper stance leg positioning during hurdle step.",
    category: "Hip Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Hurdle Step",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Standing Calf Stretch (Gastrocnemius)",
    description: "Gastrocnemius stretch addressing ankle dorsiflexion limitations affecting hurdle step clearance mechanics.",
    category: "Ankle Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Hurdle Step",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Half-Kneeling Ankle Dorsiflexion Mobilization",
    description: "Ankle dorsiflexion mobilization to restore range needed for proper knee tracking during hurdle step.",
    category: "Ankle Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Hurdle Step",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Supine Figure-4 Stretch",
    description: "Piriformis and hip ER stretch addressing posterior hip tightness that limits hurdle step hip flexion.",
    category: "Hip Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Hurdle Step",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Bird Dog - Leg slide with opposite arm lift",
    description: "Cross-body quadruped pattern for trunk anti-rotation stability during hurdle step stepping phase.",
    category: "Core Stability",
    dysfunctionType: "SMCD",
    sfmaPattern: "Hurdle Step",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Dead Bug",
    description: "Supine contralateral limb lowering for anti-extension core control during reciprocal leg movement.",
    category: "Core Stability",
    dysfunctionType: "SMCD",
    sfmaPattern: "Hurdle Step",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Step-Up",
    description: "Controlled step-up onto a box building concentric single-leg strength for hurdle step elevation.",
    category: "Functional Strength",
    dysfunctionType: "SMCD",
    sfmaPattern: "Hurdle Step",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Step-Down from Box",
    description: "Eccentric step-down for controlled single-leg lowering relevant to hurdle step deceleration.",
    category: "Functional Strength",
    dysfunctionType: "SMCD",
    sfmaPattern: "Hurdle Step",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Clamshell",
    description: "Sidelying clamshell for isolated gluteus medius activation supporting hurdle step pelvic stability.",
    category: "Hip Stability",
    dysfunctionType: "SMCD",
    sfmaPattern: "Hurdle Step",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Foam Roll IT Band",
    description: "IT band soft tissue mobilization addressing lateral thigh tightness affecting hip and knee mechanics during stepping.",
    category: "Soft Tissue Mobilization",
    dysfunctionType: "MD",
    sfmaPattern: "Hurdle Step",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Rolling Upper Body",
    description: "Upper-body rolling for trunk motor control re-education relevant to hurdle step trunk stability.",
    category: "Rolling Patterns",
    dysfunctionType: "SMCD",
    sfmaPattern: "Hurdle Step",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Rolling Lower Body",
    description: "Lower-body rolling for hip-driven patterning relevant to hurdle step hip flexion and pelvic control.",
    category: "Rolling Patterns",
    dysfunctionType: "SMCD",
    sfmaPattern: "Hurdle Step",
    recommendedForScore: "DN / DP / SMCD",
  },

  // ═══════════════════════════════════════════════════════════════
  // INLINE LUNGE (26 exercises)
  // ═══════════════════════════════════════════════════════════════
  {
    name: "Half-Kneeling Hip Flexor Stretch",
    description: "Hip flexor stretch restoring hip extension range critical for the trailing leg in the inline lunge.",
    category: "Hip Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Inline Lunge",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Half-Kneeling Ankle Dorsiflexion Mobilization",
    description: "Ankle mobilization restoring dorsiflexion range needed for lead leg knee tracking in the inline lunge.",
    category: "Ankle Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Inline Lunge",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Banded Ankle Dorsiflexion",
    description: "Band-assisted dorsiflexion for posterior talar glide addressing ankle joint restrictions in the lunge position.",
    category: "Ankle Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Inline Lunge",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Standing Calf Stretch (Gastrocnemius)",
    description: "Gastrocnemius stretch for ankle dorsiflexion range required by the inline lunge lead leg.",
    category: "Ankle Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Inline Lunge",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Standing Calf Stretch (Soleus)",
    description: "Soleus stretch for deep dorsiflexion range needed in the inline lunge lowering phase.",
    category: "Ankle Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Inline Lunge",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Supine Figure-4 Stretch",
    description: "Piriformis stretch addressing posterior hip tightness that limits inline lunge depth and pelvic control.",
    category: "Hip Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Inline Lunge",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Adductor Rockback Stretch",
    description: "Adductor stretch improving inner thigh length needed for inline lunge narrow base-of-support balance.",
    category: "Hip Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Inline Lunge",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "90/90 Hip IR Stretch",
    description: "Hip internal rotation stretch addressing rotational hip restrictions affecting inline lunge alignment.",
    category: "Hip Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Inline Lunge",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Quad/Rectus Femoris Stretch",
    description: "Quadriceps and rectus femoris stretch addressing knee flexion and hip extension restrictions for trail leg positioning.",
    category: "Hip Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Inline Lunge",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Goblet Split Squat",
    description: "Front-loaded split squat training single-leg strength and upright trunk positioning for inline lunge pattern.",
    category: "Lunge Patterns",
    dysfunctionType: "SMCD",
    sfmaPattern: "Inline Lunge",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Reverse Lunge",
    description: "Backward stepping lunge building eccentric single-leg control and deceleration capacity for lunge pattern.",
    category: "Lunge Patterns",
    dysfunctionType: "SMCD",
    sfmaPattern: "Inline Lunge",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Forward Lunge",
    description: "Forward stepping lunge for concentric single-leg strength and deceleration in the inline lunge pattern.",
    category: "Lunge Patterns",
    dysfunctionType: "SMCD",
    sfmaPattern: "Inline Lunge",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Half-Kneeling Pallof Press",
    description: "Anti-rotation press from half-kneeling training core stability in the narrow base relevant to inline lunge.",
    category: "Core Stability",
    dysfunctionType: "SMCD",
    sfmaPattern: "Inline Lunge",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Half-Kneeling Chop",
    description: "Diagonal chop pattern from half-kneeling for rotational stability and weight shift control in lunge positions.",
    category: "Core Stability",
    dysfunctionType: "SMCD",
    sfmaPattern: "Inline Lunge",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Half-Kneeling Lift",
    description: "Diagonal lift pattern from half-kneeling for anti-lateral flexion stability and upward force production.",
    category: "Core Stability",
    dysfunctionType: "SMCD",
    sfmaPattern: "Inline Lunge",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Leg Lock Bridge",
    description: "Leg-locked bridge for glute activation foundational to hip extension control in the lunge stance phase.",
    category: "Glute Activation",
    dysfunctionType: "SMCD",
    sfmaPattern: "Inline Lunge",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Single-Leg Bridge",
    description: "Unilateral bridge for hip extension strength needed to maintain pelvic position during inline lunge.",
    category: "Hip Stability",
    dysfunctionType: "SMCD",
    sfmaPattern: "Inline Lunge",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Lateral Band Walk",
    description: "Resisted side-stepping for gluteus medius activation supporting frontal plane stability in the inline lunge.",
    category: "Hip Stability",
    dysfunctionType: "SMCD",
    sfmaPattern: "Inline Lunge",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Single-Leg Romanian Deadlift",
    description: "Unilateral hip hinge for posterior chain strength and single-leg balance relevant to lunge deceleration.",
    category: "Functional Strength",
    dysfunctionType: "SMCD",
    sfmaPattern: "Inline Lunge",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Step-Down from Box",
    description: "Controlled eccentric step-down for single-leg knee and hip control relevant to inline lunge lowering.",
    category: "Functional Strength",
    dysfunctionType: "SMCD",
    sfmaPattern: "Inline Lunge",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Foam Roll Quadriceps",
    description: "Quadriceps soft tissue mobilization addressing anterior thigh restrictions affecting inline lunge depth.",
    category: "Soft Tissue Mobilization",
    dysfunctionType: "MD",
    sfmaPattern: "Inline Lunge",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Foam Roll IT Band",
    description: "IT band mobilization addressing lateral thigh tightness affecting knee tracking in the lunge.",
    category: "Soft Tissue Mobilization",
    dysfunctionType: "MD",
    sfmaPattern: "Inline Lunge",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Foam Roll Calf",
    description: "Calf tissue mobilization for improved ankle dorsiflexion during inline lunge lead leg positioning.",
    category: "Soft Tissue Mobilization",
    dysfunctionType: "MD",
    sfmaPattern: "Inline Lunge",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Rolling Upper Body",
    description: "Upper-body rolling for trunk motor control foundational to inline lunge balance and stability.",
    category: "Rolling Patterns",
    dysfunctionType: "SMCD",
    sfmaPattern: "Inline Lunge",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Rolling Lower Body",
    description: "Lower-body rolling for pelvic motor control and hip-driven patterning relevant to lunge mechanics.",
    category: "Rolling Patterns",
    dysfunctionType: "SMCD",
    sfmaPattern: "Inline Lunge",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Walking Lunge",
    description: "Dynamic forward lunge integrating bilateral leg coordination, balance, and functional strength for lunge pattern.",
    category: "Lunge Patterns",
    dysfunctionType: "SMCD",
    sfmaPattern: "Inline Lunge",
    recommendedForScore: "DN / DP / SMCD",
  },

  // ═══════════════════════════════════════════════════════════════
  // ACTIVE STRAIGHT LEG RAISE (22 exercises)
  // ═══════════════════════════════════════════════════════════════
  {
    name: "Assisted Leg Lowering to Bolster",
    description: "Supine leg lowering with bolster target for controlled hip flexion and hamstring lengthening under core control.",
    category: "Hip Flexion Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Active Straight Leg Raise",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Active Leg Lowering to Bolster",
    description: "Unassisted supine leg lowering to bolster progressing active hip flexion range with core stabilization.",
    category: "Hip Flexion Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Active Straight Leg Raise",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Supine Hamstring Stretch (Strap-Assisted)",
    description: "Strap-assisted passive hamstring stretch addressing posterior chain length limitations affecting ASLR.",
    category: "Hamstring Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Active Straight Leg Raise",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Standing Hamstring Stretch",
    description: "Standing hamstring stretch with foot elevated, targeting hamstring extensibility in a functional position.",
    category: "Hamstring Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Active Straight Leg Raise",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Supine Adductor Stretch",
    description: "Supine gravity-assisted adductor stretch addressing inner thigh tightness that restricts hip flexion range.",
    category: "Hip Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Active Straight Leg Raise",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Half-Kneeling Hip Flexor Stretch",
    description: "Hip flexor stretch addressing iliopsoas and rectus femoris restrictions of the contralateral leg during ASLR.",
    category: "Hip Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Active Straight Leg Raise",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Supine Figure-4 Stretch",
    description: "Piriformis stretch targeting posterior hip restrictions that contribute to limited ASLR performance.",
    category: "Hip Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Active Straight Leg Raise",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Foam Roll Hamstrings",
    description: "Hamstring soft tissue mobilization with foam roller to address tissue extensibility limiting ASLR range.",
    category: "Soft Tissue Mobilization",
    dysfunctionType: "MD",
    sfmaPattern: "Active Straight Leg Raise",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Foam Roll Calf",
    description: "Calf mobilization addressing distal posterior chain tightness that may contribute to ASLR restrictions.",
    category: "Soft Tissue Mobilization",
    dysfunctionType: "MD",
    sfmaPattern: "Active Straight Leg Raise",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Foam Roll IT Band",
    description: "IT band mobilization addressing lateral restrictions that may limit hip flexion range during ASLR.",
    category: "Soft Tissue Mobilization",
    dysfunctionType: "MD",
    sfmaPattern: "Active Straight Leg Raise",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Leg Lock Bridge",
    description: "Supine leg-locked bridge for core and glute activation addressing pelvic stability deficits during ASLR.",
    category: "Core & Glute Activation",
    dysfunctionType: "SMCD",
    sfmaPattern: "Active Straight Leg Raise",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Dead Bug",
    description: "Supine contralateral limb movement for anti-extension core stability directly relevant to ASLR control.",
    category: "Core Stability",
    dysfunctionType: "SMCD",
    sfmaPattern: "Active Straight Leg Raise",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Dead Bug (Band-Resisted)",
    description: "Band-resisted dead bug increasing core stability demand with external resistance during reciprocal leg movement.",
    category: "Core Stability",
    dysfunctionType: "SMCD",
    sfmaPattern: "Active Straight Leg Raise",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Rolling Upper Body",
    description: "Upper-body rolling for fundamental trunk motor control relevant to ASLR pelvic stability.",
    category: "Rolling Patterns",
    dysfunctionType: "SMCD",
    sfmaPattern: "Active Straight Leg Raise",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Rolling Lower Body",
    description: "Lower-body rolling for hip-driven motor control and pelvic sequencing relevant to ASLR.",
    category: "Rolling Patterns",
    dysfunctionType: "SMCD",
    sfmaPattern: "Active Straight Leg Raise",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Assisted Rolling Upper body - Supine to Prone",
    description: "Facilitated rolling for trunk motor control re-education addressing stability deficits in ASLR.",
    category: "Rolling Patterns",
    dysfunctionType: "SMCD",
    sfmaPattern: "Active Straight Leg Raise",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Bird Dog - Leg slide with opposite arm lift",
    description: "Quadruped cross-body pattern for trunk stability training directly relevant to ASLR core control.",
    category: "Core Stability",
    dysfunctionType: "SMCD",
    sfmaPattern: "Active Straight Leg Raise",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Assisted Bird Dog - Leg slide",
    description: "Supported quadruped leg slide providing entry-level core stability training for ASLR deficits.",
    category: "Core Stability",
    dysfunctionType: "SMCD",
    sfmaPattern: "Active Straight Leg Raise",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Active Leg Raise with Dowel Feedback",
    description: "Active SLR with dowel pressed against the lumbar spine providing biofeedback for pelvic neutral maintenance.",
    category: "Motor Control Retraining",
    dysfunctionType: "SMCD",
    sfmaPattern: "Active Straight Leg Raise",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Cook Hip Lift",
    description: "Supine hip extension with opposite hip held in flexion, isolating glute activation while maintaining pelvic stability.",
    category: "Glute Activation",
    dysfunctionType: "SMCD",
    sfmaPattern: "Active Straight Leg Raise",
    recommendedForScore: "DN / DP / SMCD",
  },
  {
    name: "Sciatic Nerve Floss",
    description: "Neural mobilization technique targeting sciatic nerve tension that may contribute to limited ASLR range.",
    category: "Neural Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Active Straight Leg Raise",
    recommendedForScore: "DN / DP / MD",
  },
  {
    name: "Prone Knee Flexion Stretch",
    description: "Prone passive knee flexion targeting rectus femoris length that may limit contralateral hip flexion during ASLR.",
    category: "Hip Mobility",
    dysfunctionType: "MD",
    sfmaPattern: "Active Straight Leg Raise",
    recommendedForScore: "DN / DP / MD",
  },
];
